sudo: required
services:
  - docker

before_install:
  - docker build -t ajaybojedla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajaybojedla/docker-react npm run test -- --coverage

after_success:
  - docker build -t ajaybojedla/docker-react .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-736796324192"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY